# TODO: automaticall regenerate this; cron job?

brew install ack
brew install atk
brew install atkmm
brew install aubio
brew install autoconf
brew install automake
brew install awscli
brew install battery
brew install bdw-gc
brew install bison
brew install bitchx
brew install boost
brew install boost-python
brew install cabal-install
brew install cairo
brew install cairomm
brew install cmake
brew install coreutils
brew install cscope
brew install ctags
brew install diff-so-fancy
brew install dirmngr
brew install elm
brew install emacs
brew install erlang
brew install exercism
brew install ffmpeg
brew install fontconfig
brew install freetype
brew install fzf
brew install gcc
brew install gdb
brew install gdbm
brew install gdk-pixbuf
brew install gettext
brew install gh
brew install ghc
brew install ghostscript
brew install git
brew install git-extras
brew install glib
brew install glibmm
brew install gmp
brew install gnupg
brew install gnupg2
brew install go
brew install gobject-introspection
brew install gperftools
brew install gpg-agent
brew install graphviz
brew install gsl
brew install gtk+
brew install gtkmm
brew install harfbuzz
brew install heroku
brew install heroku-toolbelt
brew install hicolor-icon-theme
brew install hub
brew install icu4c
brew install imagemagick
brew install inkscape
brew install isl
brew install jbig2dec
brew install jpeg
brew install jq
brew install jruby
brew install lame
brew install leveldb
brew install libassuan
brew install libcroco
brew install libevent
brew install libffi
brew install libgcrypt
brew install libgpg-error
brew install libksba
brew install libmpc
brew install libpng
brew install librsvg
brew install libsigc++
brew install libtiff
brew install libtool
brew install libusb
brew install libusb-compat
brew install libvo-aacenc
brew install libyaml
brew install liftoff
brew install little-cms
brew install little-cms2
brew install lynx
brew install macvim
brew install mad
brew install mit-scheme
brew install mpfr
brew install mutt
brew install node
brew install numpy
brew install oniguruma
brew install openssh
brew install openssl
brew install pango
brew install pangomm
brew install pcre
brew install perl
brew install phantomjs
brew install pinentry
brew install pixman
brew install pkg-config
brew install popt
brew install postgresql
brew install pstree
brew install pth
brew install python
brew install qt
brew install qt55
brew install rbenv
brew install rcm
brew install readline
brew install reattach-to-user-namespace
brew install redis
brew install ripgrep
brew install ruby
brew install ruby-build
brew install shared-mime-info
brew install sl
brew install snappy
brew install sox
brew install spark
brew install sqlite
brew install swift
brew install the_silver_searcher
brew install tig
brew install tmux
brew install tokyo-cabinet
brew install trash
brew install tree
brew install unixodbc
brew install utf8proc
brew install v8
brew install vim
brew install vpython
brew install watchman
brew install wget
brew install wxmac
brew install wxpython
brew install x264
brew install xcproj
brew install xvid
brew install xz
brew install yarn
brew install youtube-dl
brew install zsh
