#! /usr/bin/env ruby

require 'rubygems'
require 'csv'
require 'ostruct'

def install_gem(name)
  begin
    gem name
  rescue LoadError
    $stderr.print "ruby gem '#{name}' not found, " <<
      "would you like to install it (y/N)? : "
    answer = gets
    if answer[0].downcase.include? "y"
      Gem.install name
      sleep 0.3
    else
      exit(1)
    end
  end
end

install_gem 'tod'

require 'tod'
require 'tod/core_extensions'

morning   = Tod::Shift.new(Tod::TimeOfDay.new(6), Tod::TimeOfDay.new(13), true)
afternoon = Tod::Shift.new(Tod::TimeOfDay.new(13), Tod::TimeOfDay.new(18, 30), true)
evening   = Tod::Shift.new(Tod::TimeOfDay.new(18, 30), Tod::TimeOfDay.new(23, 45), true)
night     = Tod::Shift.new(Tod::TimeOfDay.new(23, 45), Tod::TimeOfDay.new(6), true)

time_of_day = Time.now.to_time_of_day
year        = Time.now.year
month       = Time.now.month
today       = OpenStruct.new({ nba: Time.new.strftime("%a %b%e %Y"), mlb: Time.new.strftime("%m/%d/%y")})

nba_games = CSV.read("/users/ambirdsall/.dotfiles/data/celtics/#{year}/#{month}/schedule.csv")
sox_game_day = !`awk -F '"*,"*' '{print $1}' ~/.dotfiles/data/red_sox/#{year}/schedule.csv | grep '#{today}'`.empty?

=begin
  nba_games.map {|row| [row[0], row[2], row[4]] }
  => [["Date", "Visitor/Neutral", "Home/Neutral"],
      ["Thu Dec 1 2016", "Milwaukee Bucks", "Brooklyn Nets"],
      ["Thu Dec 1 2016", "Dallas Mavericks", "Charlotte Hornets"],
      ...
     ]
=end
boston_game  = ->(row) { row.any? { |col| col =~ /Boston/ } }
celtics_game_day = nba_games.map    { |row| [row[0], row[2], row[4]] }
                        .select { |row| row.first == today.nba }
                        .select(&boston_game)
                        .any?

icon = if celtics_game_day
         '🍀'
       elsif sox_game_day
         '⚾️'
       elsif morning.include?(time_of_day)
         '☕️'
       elsif afternoon.include?(time_of_day)
         %w(🙈 🙉 🙊).sample
       elsif evening.include?(time_of_day)
         '🍺'
       elsif night.include?(time_of_day)
         '🌒'
       end

print icon
