#! /usr/bin/env ruby

require 'rubygems'

def install_gem(name)
  begin
    gem name
  rescue LoadError
    $stderr.print "ruby gem '#{name}' not found, " <<
      "would you like to install it (y/N)? : "
    answer = gets
    if answer[0].downcase.include? "y"
      Gem.install name
    else
      exit(1)
    end
  end
end

install_gem 'tod'

require 'tod'
require 'tod/core_extensions'

morning = Tod::Shift.new(Tod::TimeOfDay.new(6), Tod::TimeOfDay.new(13), true)
afternoon = Tod::Shift.new(Tod::TimeOfDay.new(13), Tod::TimeOfDay.new(18, 30), true)
evening = Tod::Shift.new(Tod::TimeOfDay.new(18, 30), Tod::TimeOfDay.new(23, 45), true)
night = Tod::Shift.new(Tod::TimeOfDay.new(23, 45), Tod::TimeOfDay.new(6), true)

now = Time.now.to_time_of_day

icon = if morning.include?(now)
         '☕️'
       elsif afternoon.include?(now)
         %w(🙈 🙉 🙊).sample
       elsif evening.include?(now)
         '🍺'
       elsif night.include?(now)
         '🌒'
       end

print icon
