#!/bin/sh

if [ "$(uname)" = "Darwin" ]; then
  osascript -e 'tell application "Spotify" to if player state is playing then " ▶ #[fg=cyan]" & name of current track & "#[fg=default] - #[fg=blue]" & artist of current track' | tr -d "\n"
  osascript -e 'tell application "Spotify" to if player state is paused then " #[fg=cyan]" & name of current track & "#[fg=default] - #[fg=blue]" & artist of current track' | tr -d "\n"
fi
